# tuple of index, used_vars, priority
UNION = 0, (1, 2), 1
COMPLEMENT_X = 1, (1, 2), 1
COMPLEMENT_Y = 2, (2, 1), 1
INTERSECTION = 3, (1, 2), 2
COMPOSITION_X = 4, (1, 2), 3
COMPOSITION_Y = 5, (2, 1), 3
POWER_SET_X = 6, (1,), 4
POWER_SET_Y = 7, (2,), 4
CONVERSE_RELATION_X = 8, (1,), 3
CONVERSE_RELATION_Y = 9, (2,), 3
REFLEXIVE_CLOSURE_X = 10, (1,), 2
REFLEXIVE_CLOSURE_Y = 11, (2,), 2
TRANSITIVE_CLOSURE_X = 12, (1,), 2
TRANSITIVE_CLOSURE_Y = 13, (2,), 2

CHOOSE_BY_INDEX = (UNION, COMPLEMENT_X, COMPLEMENT_Y, INTERSECTION, COMPOSITION_X, COMPOSITION_Y, POWER_SET_X,
                   POWER_SET_Y, CONVERSE_RELATION_X, CONVERSE_RELATION_Y, REFLEXIVE_CLOSURE_X, REFLEXIVE_CLOSURE_Y,
                   TRANSITIVE_CLOSURE_X, TRANSITIVE_CLOSURE_Y)
